### PR TITLE
Feature/unit test

### PR DESCRIPTION
**Pull request by jonyeezs**
To keep it simple, we won't convert the project to a node modules.

KISS this by only testing as it is. Thus, utils won't be tested.

~Due to the way the code's been structured for html, testing isn't easy with the available JS test framework.~

~I'm not sure if there is any nice ones out there that cater to html js. Because of that we'll need to do some restructuring.~

Below are all the steps needed to complete this PR:

~- [x] Restructure app to be modular~
- [x] Install test frameworks
- [x] Test utils.js
- [ ] Test script.js
- [ ] Test server.js

----

Work needed for restructure:

* Need to export code so that it can be imported for testing.
* IIFE is needed so will need to bundle the code.
* Use Browserify for bundling as it supports node's `require`.
* Convert public -> lib folder. Makes more sense as it contains the libraries for the app; and allows the server to serve from the same dir.
* Needed to add more npm scripting to bundle code. Moved all required code to public for easy page loading.
* Now has `npm start` which just starts the app without a daemon.

### CODE REVIEW

**Comment by jonyeezs** [comment]
I think I may have to retract my first comment on the issue tracker. This isn't easily unit testable as i thought.
It's written heavily browser focus.

I think we'r better off having as a UI test, rather than a unit test in its actual context.

I have no idea how people would test their code before the arrival of node!

browserifying your app may seem heavy, but it allows for easy testing of the app.
It actually feels more dirty trying to test it as browser code.

I'll see how far i can go with dom testing.

I am determine to get unit test for you!

**Comment by jonyeezs** [comment]
huzzah! Manage to test utils with jsdom - very cool :dark_sunglasses:

**Comment by benjaminhr** [comment]
Great! So how far have you gotten with the tests? Any major pitfalls?

**Comment by benjaminhr** [comment]
Also love the emojis in your commit messages :100:

**Comment by jonyeezs** [comment]
>Great! So how far have you gotten with the tests? Any major pitfalls?
struggling with script.js.

2 issues:

1. `showdown` and `sharejs` are inline downloaded scripts. Need to somehow stub and mock them.
2. `window.location.href` is broken on JSDOM. They have a workaround, gonna see if that works out.

**Comment by benjaminhr** [comment]
Why do you need `window.location.href`, if you're testing the GUID? Wouldn't `window.location.pathname` be better suited?

**Comment by benjaminhr** [comment]
Do you think using sharejs, and showdown as modules would work?

**Comment by jonyeezs** [comment]
>Why do you need window.location.href, if you're testing the GUID? Wouldn't window.location.pathname be better suited?

The problem isn't in the test suite, it's in the actual onLoad script (https://github.com/benjaminr177/editor/blob/master/public/script.js#L8). When executing the code in JSDOM it fails, because:

>Currently jsdom has dummy behaviors for (the ability to change the global object, and all other objects, when clicking a link or assigning location.href or similar.), such as sending a "not implemented" "jsdomError" to the virtual console for navigation

The work around suggestion is: _creating new JSDOM instances for each page you "navigate" to during a crawl_. No idea how to do that as yet.

> Do you think using sharejs, and showdown as modules would work?

I found the solution. Look at the last draft commit.

**Comment by benjaminhr** [comment]
Is this ready for a merge?

**Comment by jonyeezs** [comment]
No. Not yet. Still pending two items on the list.

**Comment by jonyeezs** [comment]
@benjaminr177 unfortunately it has been a challenge to unit test a code that is coupled to the DOM heavily.

I reckon a UI testing tool would be way easier, like selenium or cypress.

If you still want quicker test, ie unit test, modularizing your code is still the easiest to manage; which will need a bundler like browserify.

What your thoughts? Your call. This has been an interesting experience for me :roller_coaster: 

edit: i can rewrite the commits to only have a setup to test utils.js

**Comment by benjaminhr** [comment]
Well I guess this would be a good point to let go 😄  Thanks for the help though, I learnt a couple useful things from you.

**Pull request closed without merging**
